// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NamazTimeApp.Data.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NamazTimeApp.Data.Infrastructure.Migrations
{
    [DbContext(typeof(AppMigrationDbContext))]
    partial class AppMigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NamazTimeApp.Master.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CREATED_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DELETED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DELETED_BY")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("boolean");

                    b.Property<string>("RECORD_SOURCE_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UPDATED_ID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("AppSetting", "NAMAZTIMEAPP_MASTER");
                });

            modelBuilder.Entity("NamazTimeApp.Master.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CREATED_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DELETED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DELETED_BY")
                        .HasColumnType("integer");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RECORD_SOURCE_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UPDATED_ID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Location", "NAMAZTIMEAPP_MASTER");
                });

            modelBuilder.Entity("NamazTimeApp.Master.PrayerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CREATED_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DELETED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DELETED_BY")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RECORD_SOURCE_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UPDATED_ID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PrayerType", "NAMAZTIMEAPP_MASTER");
                });

            modelBuilder.Entity("NamazTimeApp.Notification.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CREATED_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DELETED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DELETED_BY")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeviceRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("boolean");

                    b.Property<string>("NotificationBody")
                        .HasColumnType("text");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("PrayerDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PrayerTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RECORD_SOURCE_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UPDATED_ID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceRegistrationId");

                    b.HasIndex("PrayerTypeId");

                    b.ToTable("NotificationLog", "NAMAZTIMEAPP_NOTIFICATION");
                });

            modelBuilder.Entity("NamazTimeApp.Transaction.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CREATED_ID")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentFcmToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DELETED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DELETED_BY")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceUniqueId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NotificationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RECORD_SOURCE_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UPDATED_ID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUniqueId")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("DeviceRegistration", "NAMAZTIMEAPP_TRANSACTION");
                });

            modelBuilder.Entity("NamazTimeApp.Transaction.PrayerTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Asr")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CREATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CREATED_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DELETED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DELETED_BY")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Dhuhr")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Fajr")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IS_ACTIVE")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("Isha")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Maghrib")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("PrayerDate")
                        .HasColumnType("date");

                    b.Property<string>("RECORD_SOURCE_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly>("Sunrise")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UPDATED_ID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "PrayerDate")
                        .IsUnique();

                    b.ToTable("PrayerTime", "NAMAZTIMEAPP_TRANSACTION");
                });

            modelBuilder.Entity("NamazTimeApp.Notification.NotificationLog", b =>
                {
                    b.HasOne("NamazTimeApp.Transaction.DeviceRegistration", "DeviceRegistration")
                        .WithMany()
                        .HasForeignKey("DeviceRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NamazTimeApp.Master.PrayerType", "PrayerType")
                        .WithMany()
                        .HasForeignKey("PrayerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceRegistration");

                    b.Navigation("PrayerType");
                });

            modelBuilder.Entity("NamazTimeApp.Transaction.DeviceRegistration", b =>
                {
                    b.HasOne("NamazTimeApp.Master.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NamazTimeApp.Transaction.PrayerTime", b =>
                {
                    b.HasOne("NamazTimeApp.Master.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
